### ISSUE TITLE
Refactor CI

### ISSUE THREAD

**Issue by adamhutchings** [y-flat/yfc#105]
Right now, each of the three checks separately compiles the yfc executable. We need it to only compile once, and if the compilation fails, don’t try to run the other two workflows.

**Comment by Sophon96** [comment]
I feel the best way to do this is to actually refactor the workflows to have one for each platform (Linux, MacOS, and Windows (if we care about that)). The current workflow times seem pretty low, and there's not too much activity going on, so we shouldn't hit the 2000 minute limit.

**Comment by adamhutchings** [comment]
Alright, that sounds like a good idea. Just Linux and Mac for now, because there’s a 0% chance that this compiles on Windows.

**Comment by Sophon96** [comment]
👍🏻

**Comment by JakeRoggenbuck** [comment]
We should have a workflow that makes sure no one ports this to windows
