### ISSUE TITLE
Add identifier output correctly

### ISSUE THREAD

**Issue by adamhutchings** [y-flat/yfc#64]
Identifiers need to be output in a way that won't conflict across files. Such as:
`path$to$file$$identifier_name`

**Comment by dekrain** [comment]
Shouldn't you add this to #104 instead of closing it immediately?

**Comment by adamhutchings** [comment]
I completely forgot that #104 was still an open PR.

**Comment by dekrain** [comment]
No worries, I took care of that that myself.

**Comment by adamhutchings** [comment]
Big brain Adam moment
