### ISSUE TITLE
Validator uses wrong type enums

### ISSUE THREAD

**Issue by dekrain** [y-flat/yfc#71]
In `validate_binary`, and perhaps in other places, it checks that the parse node type is a value, instead of the expression's type. This should cause wrong behaviour as `YFCS_VALUE (0) != YFCS_EXPR (1)`.
Maybe use a different naming scheme not to make the namespaces collide or remove the parse node entirely.

**Comment by dekrain** [comment]
In fact, it seems like parse node's type isn't even set in the first place.

**Comment by adamhutchings** [comment]
Alright, I will definitely refactor the naming scheme. I wonder if there are any languages that compile to C with better naming schemes built-in to the language?
Oh wait ...

**Comment by dekrain** [comment]
`Cfront`?

**Comment by adamhutchings** [comment]
🟨🟩⬛⬛⬛⬛

**Comment by dekrain** [comment]
> `Cfront`?

```c
int a123456789 = 1; /* if this does not compile get a better C compiler */
int a123456780 = 2;
```

**Comment by adamhutchings** [comment]
Is that code actually in CFront?

**Comment by dekrain** [comment]
Yes, it's in `C++ 3.0.3/source/szal.c`, which checks if the C compiler trims long identifiers (\*_cough_\* https://github.com/y-flat/yfc/blob/f246585987f09bb86efa3466935b973ffaab6e38/src/lexer/lexer.c#L201 *\_cough\_*).

**Comment by adamhutchings** [comment]
Hmmm, doesn't sound familiar at all.

**Comment by adamhutchings** [comment]
> Yes, it's in `C++ 3.0.3/source/szal.c`, which checks if the C compiler trims long identifiers (*_cough_*
> 
> https://github.com/y-flat/yfc/blob/f246585987f09bb86efa3466935b973ffaab6e38/src/lexer/lexer.c#L201
> 
> __cough__).
> Worth to mention is that `szal.c`'s purpose is to probe host compiler's type sizes & alignment to be used in the C++ compiler.

@dekrain speaking of, do you think this is an issue worth fixing?

**Comment by dekrain** [comment]
Yes, I can do that soon.
