### ISSUE TITLE
Add a “tests - passing” badge

### ISSUE THREAD

**Issue by adamhutchings** [y-flat/yfc#84]
Or failing, as the case hopefully should not be.

**Comment by RishiKumarRay** [comment]
@adamhutchings does the valgrind checks for the tests?

**Comment by adamhutchings** [comment]
The first test called `compiler` compiles the code and runs the tests, so it might need to be made into two separate files, now that I think about it.

**Comment by RishiKumarRay** [comment]
@adamhutchings if you want to add badge then either make a new file or we can simply add another bade for compiler file and rename it to tests 🤔 let me know what you think

**Comment by adamhutchings** [comment]
We would need to separate the code that runs tests into a separate testing workflow file.

**Comment by RishiKumarRay** [comment]
@adamhutchings i can do that , if you create another issue for that please assign me i will take both the issues.

**Comment by adamhutchings** [comment]
I’m not able to assign you through GitHub, but I did open the other issue and you can do them both. Thank you so much!

**Comment by RishiKumarRay** [comment]
@adamhutchings please review
